targets:
  $default:
    builders:
      json_serializable:
        enabled: true

        options:
          explicit_to_json: true
          include_if_null: false
          any_map: true

      freezed|freezed:
        enabled: true

      injectable_generator|injectable_builder:
        enabled: true

      injectable_generator|injectable_config_builder:
        enabled: true
