name: farmbot
description: A Dart Farmbot RPC wrapper
version: 0.0.1
homepage: https://github.com/mrgnhnt96/farm_bot

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async:
  meta:
  stack_trace:


dev_dependencies:
  fake_async:
  matcher:
  test: