name: farmbot
description: A Dart Farmbot RPC wrapper
version: 0.0.1
homepage: https://github.com/mrgnhnt96/farm_bot

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async:
  derry: ^1.4.1
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.3

  meta:
  mqtt_client: ^9.3.1
  stack_trace:

dev_dependencies:
  build_runner:
  fake_async:
  freezed: ^0.14.2
  matcher:
  test:

import_sorter:
  comments: false

scripts: derry.yaml
