name: models
description: Models for the farmbot project
publish_to: none
version: 0.0.1
homepage: https://github.com/mrgnhnt96/farm_bot

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.3

dev_dependencies:
  build_runner:
  freezed: ^0.14.2
  derry: ^1.4.1
  matcher:
  test:

import_sorter:
  comments: false

scripts: ../../derry.yaml
